"""add gender to user

Revision ID: 849b057d03a4
Revises: d4839c8481de
Create Date: 2026-04-14 08:35:48.924713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849b057d03a4'
down_revision: Union[str, Sequence[str], None] = 'd4839c8481de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        'ALTER TABLE report ALTER COLUMN final_report TYPE JSONB USING final_report::jsonb'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'final_report',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###
