"""fix embedding dimensions to 384

Revision ID: 96c77f20e3ae
Revises: 9ff550c85598
Create Date: 2026-03-22 22:34:13.214034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import vector


# revision identifiers, used by Alembic.
revision: str = '96c77f20e3ae'
down_revision: Union[str, Sequence[str], None] = '9ff550c85598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'embedding_e5',
               existing_type=vector.VECTOR(dim=512),
               type_=vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entry', 'embedding_e5',
               existing_type=vector.VECTOR(dim=384),
               type_=vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
